# Site wide configuration

title: Niaj-scio
description: "Descubriendo un nuevo aprendizaje en la mensajería"
logo: 120x120.png
teaser: 400x250.png
locale: es_ES
author: Sangui.net
url: //sanguinet.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Niaj-scio
  web: 
  email: niaj-scio@outlook.com
  twitter: niaj-scio
  bio: "Sitio web para aprender y mejorar la mensajería Telegram y otras posibilidades en rumbos."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname: niajscio


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
